.PHONY: zip run

test:
	./run wiki-sdom.nfg output-wiki-sdom.txt
	./run example1.nfg output-example1.txt
	./run example2.nfg output-example2.txt
	./run example3.nfg output-example3.txt

zip: 
	zip Assignment1_2_16.zip README.md makefile solve.py run
