.PHONY: q1 q2 q3 zip
all: q1 q2 q3

q1:
	python2.7 pyspark_1.py q1.csv

q2:
	python2.7 pyspark_2.py q2.csv


q3:
	python2.7 pyspark_3.py q3.csv

zip:
	zip 20161105_Assignment4.zip pyspark_1.py pyspark_2.py pyspark_3.py README.md
